export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const SET_ERRORS = 'SET_ERRORS'
export const SET_LOADING = 'SET_LOADING'
export const GECKO_PING = 'GECKO_PING'
export const GECKO_COINS_LIST = 'GECKO_COINS_LIST'
export const GECKO_COINS_MARKETS = 'GECKO_COINS_MARKETS'
export const GECKO_COINS_CURRENT = 'GECKO_COINS_CURRENT'
export const FETCH_ALL_USERS = 'FETCH_ALL_USERS'
export const FETCH_COINS = 'FETCH_COINS'
export const SET_CURRENT_INNER_COIN = 'SET_CURRENT_INNER_COIN'
export const SET_TABLE_RATE_LIMIT = 'SET_TABLE_RATE_LIMIT'
export const SET_TOP_COINS_GECKO = 'SET_TOP_COINS_GECKO'


export const FETCH_REFERRAL_LINKS = 'FETCH_REFERRAL_LINKS'

// sorting coin
export const SET_SORTING_NAME = 'SET_SORTING_NAME'
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE'
export const SET_PAGE_LIMIT = 'SET_PAGE_LIMIT'
export const SET_SEARCHING_WORD = 'SET_SEARCHING_WORD'
export const SET_IS_TIMER_FILTER = 'SET_IS_TIMER_FILTER'

export const CREATE_VOTE = 'CREATE_VOTE'
export const FETCH_VOTES = 'FETCH_VOTES'
export const FETCH_CURRENT_VOTES = 'FETCH_CURRENT_VOTES'
export const ADD_CURRENT_VOTE = 'ADD_CURRENT_VOTE'

export const ADD_COIN = 'ADD_COIN'
export const ADD_CHAINS = 'ADD_CHAINS'
export const REMOVE_CHAIN = 'REMOVE_CHAIN'
export const ADD_NEW_CHAIN = 'ADD_NEW_CHAIN'

export const FETCH_SUBSCRIBERS = 'FETCH_SUBSCRIBERS'

export const SET_TOP_COINS_BY_HOUR = 'SET_TOP_COINS_BY_HOUR'
export const SET_TOP_COINS_BY_DAY = 'SET_TOP_COINS_BY_DAY'
export const SET_TOP_COINS_BY_WEEK = 'SET_TOP_COINS_BY_WEEK'

export const SET_LEADERS_COINS_BY_DAY = 'SET_LEADERS_COINS_BY_DAY'
export const SET_LEADERS_COINS_BY_WEEK = 'SET_LEADERS_COINS_BY_WEEK'
export const SET_LEADERS_COINS_BY_MARKET_CAP = 'SET_LEADERS_COINS_BY_MARKET_CAP'
export const SET_THE_BEST_LEADER = 'SET_THE_BEST_LEADER'

export const FETCH_NOTIFICATIONS = 'FETCH_NOTIFICATIONS'
